rainforest/config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do 
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :users, :only => [:new, :create] #this can probably be formated like below
  resources :sessions, only: [:new, :create, :destroy]

end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end

	has_many :reviews
	has_many :users, through: :reviews
end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base

	validates :comment, :presence => true
	
	belongs_to :user
	belongs_to :product
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, through: :reviews

	validates :name, :email, presence: true
	
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end



  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.order('products.created_at DESC')
    end.page(params[:page])

    respond_to do |format|
      format.js
      format.html
    end
      
  # for use with $ajax and longer $.get request
    # if request.xhr?
    #   render @products
    # end
  end

  def show
  	@product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)

  	if @product.save
  		redirect_to products_url
  	else
  		render :new
  	end
  end

  def update
  	@product = Product.find(params[:id])

  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end		
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to product_path
  end

  private
  def product_params
  	params.require(:product).permit(:name, :url, :description, :price_in_cents)
  end
  	
end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  	
  	before_filter :ensure_logged_in, only: [:create, :destroy]
  	before_filter :load_product

    def show
    	@review = Review.find(params[:id])
    end

    def create
    	@review = @product.reviews.build(review_params)
    	@review.user = current_user

      respond_to do |format|
        if @review.save
          format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
          format.js {} 
        else
          format.html { render 'products/show', alert: 'There was an error.' }
          format.js {}
        end
      end
    end

    def destroy
    	@review = Review.find(params[:id])
    	@review.destroy
    end

    private
    def review_params
    	params.require(:review).permit(:comment, :product_id)
    end

    def load_product
    	@product = Product.find(params[:product_id])
    end

  end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :exception


  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or passowrd"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, notice: "logged out"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to products_url, notice: "Signed up!"
  	else
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest/app/helpers/users_helper.rb
module UsersHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag 'styles.css' %>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
 <%= html_import_tag 'application'%>
</head>
<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p> 
  <% end %>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to "∞", root_path, :class => 'navbar-brand'  %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us" %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">

        <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
          <%= text_field_tag :search, params[:params], :input_type =>'text', :class => 'form-control', :placeholder =>'search' %>
        </div> 
          <%= submit_tag "Search", :type => 'submit', :class => 'btn btn-default' %>
          <% end %>
        </form>

        <li class="nav-link-match">
          <% if current_user %>Hello, <strong><%= current_user.name %></strong>.
        </li>
        <li> 
            <%= link_to "Log out", session_path("current"), :method => :delete %>
        </li>
          <% else %>
        <li>
            <%= link_to "Log in", new_session_path %> 
        </li>
        <li>
            <%= link_to "Sign up", new_user_path %>
        </li>
          <% end %>
        <!-- <li><%= link_to "Log in", new_session_path %></a></li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="top-menu-block">
  <div class="welcome"><u class="colored-four">BUY</u> ONE <u class="colored-four">GET</u> ONE 50% off</p>
  </div>
  <div class="main-title <%= "flipInX animated" if params[:action] == "index" and params[:controller] == "products" %>">
    <h1 class="main-title"><span style="font-family:Entypo; color:#FF3D2E">∞</span> Chachka's</h1>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8"><%= yield %></div>
    <div class="col-xs-2"></div>
  </div>
</div>



</body>
</html>

rainforest/app/views/products/_form.html.erb
<hr></hr>
<%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<br />
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name, :class => 'form-control', :placeholder => 'product name' %>
	</div>
	<br />
	<div class="field">
		<%= f.label :url %><br />
		<%= f.text_field :url, :class => 'form-control', :placeholder => 'image name' %>
	</div>
	<br />
	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description, :class => 'form-control', :rows => '3', :placeholder => 'product description' %> 
	</div>
	<br />
	<div class="field">
		<%= f.label :price_in_cents %><br />
		<%= f.number_field :price_in_cents, :class => 'form-control', :placeholder => '$1/100' %>
	</div>
	<br />
	<div class='actions' >
		<%= f.submit :class => 'btn btn-lg btn-primary btn-block green' %>
	</div>
<% end %>

rainforest/app/views/products/_product.html.erb
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= product.url %>" alt="..."> 
      <div class="caption">
      <p class="card-product-link-headers"> <%= link_to product.name, "/products/#{product.id}" %></h3>
       <p><%= product.description %></p>
      </div>
    </div>
  </div>

rainforest/app/views/products/_products.html.erb
<% @products.each_slice(3) do |slice| %>
 	<div class="row">
		<%= render slice %>
	</div>
<% end %>

rainforest/app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
 	<% @review.errors.full_messages.each do |error| %>
  		 <div class="alert">
    			<h3 class="alert alert-danger" role="alert"><%= error %></h3>
   		</div>
 	<% end %>
<% end %>

rainforest/app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
	<p><%= review.comment %><br>
		<% if review.user != nil %>
		<em> by <strong><%= review.user.name %></strong></em> Added on: <%= review.created_at %>
		<% end %>
	</p> 
<% end %>

rainforest/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<div class="underline"></div>

<%= render 'form' %>

<h3><%= link_to 'Back', products_path %></h3>

rainforest/app/views/products/index.html.erb
<!-- <h1 id="main-title-header">Rainforest Products</h1> -->

<h3><%= link_to "ADD A PRODUCT", new_product_path, :class => "add-product-header"%></h3>
<p class="page-entries"><%= page_entries_info @products %></p>

<div id="products">
	<%= render partial: 'products' %>
</div>

<p><%= paginate @products %></p>

rainforest/app/views/products/index.js.erb
$('#products').append('<%= j render(partial: 'products') %>');
$('.pagination').replaceWith('<%= j paginate(@products) %>');

rainforest/app/views/products/new.html.erb
<h1 class="basic-header">NEW PRODUCT</h1>

<div class="underline"></div>

<%= render 'form' %>

<!-- <h2><%= link_to 'Back', products_path %></h2> -->

rainforest/app/views/products/show.html.erb
<div class="centered-back">

<br /><br />

<div class="centered-product">
	<%= link_to "Back to Products", products_url, :class => "page-entries" %> | <%= link_to "Edit", edit_product_path(@product), :class => "page-entries" %>
</div>
	<h3 class="show-product-header"><%= @product.name %></h3><br /> 
	<%= image_tag @product.url %>
	<br />
	<br />
	<p><%= @product.description %>, <%= @product.price_in_cents %></p>
	<p><%= @product.formatted_price %></p>
</div>

<% if current_user %>
	<h3>Reviews</h3>

	<p>Reviews for <%= @product.name %></p> 

	<div id="review-list">
		<%= render :partial => "reviews" %>
	</div>

	<h3>New Review</h3> 
	
	<%= form_for([@product, @review], :remote => true) do |f| %>
			<div id="review-form-errors">
   				<%= render :partial => "/products/review_form_errors" %>
			</div>

		<div class"field">
			<%= f.label :comment %><br />
			<%= f.text_area :comment, :class => 'form-control', :row => '3' %>
		</div>
		<br />
		<div>
			<%= f.submit :class => 'btn btn-lg btn-primary btn-block green' %>
		</div>
		<% end %>
	<% else %>
		<p>Please <%= link_to "log in", new_session_path %> to add or see reviews.</p>
<% end %>

rainforest/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

rainforest/app/views/reviews/create.js.erb
<% if @review.errors.present? %>
	  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
	$("#review-list").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");
	$("#new_review")[0].reset();
<% end %>

rainforest/app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

rainforest/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

rainforest/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rainforest/app/views/users/new.html.erb
<h1 class="basic-header">SIGN UP</h1>
<hr></hr>
<br />
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for messages in @user.errors.full_messages %>
				<li><%= messages %></li>
			<% end %>
		</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name, :class => 'form-control', :placeholder => 'name'%><br />
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email, :class => 'form-control', :placeholder => 'email' %><br />
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password, :class => 'form-control', :placeholder => 'password' %><br />
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => 'confirm password' %><br />
	</div>
	<br />
	<div class="actions">
		<%= f.submit :type => 'button', :class => 'btn btn-lg btn-primary btn-block' %>
	</div>
<% end %>